### PR TITLE
Add SAML2 login method helper

### PR DESCRIPTION
**Pull request by muthusuba**
This is in reference to the SAML2 work on Synapse.

Sign-off: Muthu Subramanian <muthu.subramanian.karunanidhi@ericsson.com>

### CODE REVIEW

**Comment by Kegsay** [comment]
ok to test

**Comment by Kegsay** [comment]
The `client` instance is from `matrix-js-sdk`, and as such does not know about `loginWithSAML2` so trying to call this will fail. I'm happy to merge this in provided you aware of this?

**Comment by Kegsay** [comment]
Related: https://github.com/matrix-org/matrix-js-sdk/pull/15

Heads up that `matrix-angular-sdk` is using an older version of `matrix-js-sdk` ("0.0.4-a" on NPM) so you may need to make sure the interface that angular is using meets 0.1.2.

**Comment by muthusuba** [comment]
Thank you so much!

**Pull request merged**
